
name: Build and Push Docker Image &run on ec2 under docker compose

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} \
            -f employee-app/Dockerfile \
            employee-appgit 

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "employee-app/docker-compose.yml"
          target: "/home/ec2-user/myapp"
          strip_components: 1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "employee-app/docker-compose.yml"
          target: "/home/ec2-user/myapp"
        strip_components: 1
          script: |
            cd /home/ubuntu/myapp

            echo "Updating image tag..."

            cat > .env << EOF
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            IMAGE_TAG=${{ github.sha }}
            EOF

            docker compose pull

            docker compose up -d

            docker image prune -f



