name: Build and Push Docker Image & Run on EC2

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} \
            -f employee-app/Dockerfile \
            employee-app


      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}


      - name: Copy Docker Compose and SQL Schema to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            employee-app/docker-compose.yml
            employee-app/schema.sql
          target: "/home/ec2-user/myapp"
          strip_components: 1


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |

            cd /home/ec2-user/myapp

            echo "Updating image tag..."

            cat > .env << EOF
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            IMAGE_TAG=${{ github.sha }}
            EOF

            echo "Pulling new Docker image..."

            docker compose pull

            echo "Starting application..."

            docker compose up -d

            echo "Removing unused images..."

            docker image prune -f

            echo "Deployment completed successfully."

            echo "Running containers:"

            docker compose ps